name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: all
      run: make all
    - name: clean
      run: make clean
    - name: re
      run: make re
    - name: fclean
      run:  make fclean
