name: BUILD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependences
      run: sudo apt-get install xorg libxext-dev libbsd-dev
    - name: git submodule
      run: git submodule update --init
    - name: all
      run: make all
    - name: clean
      run: make clean
    - name: re
      run: make re
    - name: fclean
      run:  make fclean
